version: '3.8'

services:
  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: MedGPT_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./Client/.env
    depends_on:
      - backend
    volumes:
      - ./Client/src:/app/src
      - ./Client/public:/app/public

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: MedGPT_backend
    ports:
      - "3000:3000"
    env_file:
      - ./Server/.env
    environment:
      - DATABASE_URL=postgresql://postgres:Saha%4006122004@db:5432/MedGPT_DB
      - RAG_SERVICE_URL=http://rag-service:8000
    depends_on:
      - db
      - rag-service
    volumes:
      - ./Server/src:/app/src
      - ./Server/prisma:/app/prisma

  rag-service:
    build:
      context: ./Server/services
      dockerfile: Dockerfile
    container_name: MedGPT_rag
    ports:
      - "8000:8000"
    env_file:
      - ./Server/.env
    volumes:
      - ./Server/services:/app

  db:
    image: postgres:15-alpine
    container_name: MedGPT_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Saha@06122004
      POSTGRES_DB: MedGPT_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
